FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /workspaces
COPY . ./server/

WORKDIR /workspaces/server

RUN dotnet restore

RUN export PATH="$PATH:/root/.dotnet/tools"

ENV DOTNET_ENVIRONMENT=Development

CMD ["/bin/bash"]